import "./globals.css";

export const metadata = {
    title: {
        default: "Feedback App",
        template: "%s | Feedback App",
    },
    description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body className="relative w-full h-screen">{children}</body>
        </html>
    );
};

export default RootLayout;
